### ISSUE TITLE
Testing and I noticed that this adds the ^M Microsoft Line endings

### ISSUE THREAD

**Issue by lathama** [anaggh/bludit-scripts#5]
Testing and I noticed that this adds the ^M Microsoft Line endings. I am not sure that this was desired.

**Comment by anaggh** [comment]
Is it related to this ?
```
    $compulsoryBluditLine = "<?php defined('BLUDIT') or die('Bludit CMS.'); ?>".PHP_EOL;
```
If the script is run on Windows machine, it will add Microsoft Line endings. If *nix, it should add *nix line endings.

**Comment by lathama** [comment]
More details, Testing script on webhosting platform on Ubuntu. I noticed it and will update when I find the exact issue.

So yes, running on Linux. I did not expect it so I captured with an issue here. Give me an hour to update with findings.

**Comment by anaggh** [comment]
Sure! I have migrated a Bludit installation on Ubuntu 16.04 without any issues.

**Comment by lathama** [comment]
I just used https://bjarneo.codes/use-php_eol-instead-newline-characters-php-output/ to validate that PHP_EOL is creating Unix line returns.

uname -a
Linux vendorreplacedhere.com 4.4.0-93-generic #116~14.04.1 SMP Tue Aug 29 09:41:38 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

still checking

**Comment by lathama** [comment]
ugh, sorry, so for what ever reason bludit 1.6.2 is saving the index.txt files for posts and pages with the ^M dos line endings. Your script just uses copy so not an issue with your script.

closing this as I should have validated more, sorry for the noise.
